### ISSUE TITLE
some issues after upgrading the LBS server to Fedora 23

### ISSUE THREAD

**Issue by tpokorra** [SolidCharity/LightBuildServer#144]
* during the nightly triggered builds, one job just hangs, without a machine being started
* creating a new job, while all machines are busy, results in nothing

in the log file I see

```
Unexpected error: <class 'ValueError'>
(<class 'ValueError'>, ValueError('parameters are of unsupported type',), <traceback object at 0x7fcf1505ca88>)
[pid: 16201|app: 0|req: 8372/8372] 127.0.0.1 () {34 vars in 428 bytes} [Sat Jan 16 07:59:01 2016] GET /processbuildqueue => generated 0 bytes in 1315 msecs (HTTP/1.1 200) 2 headers in 78 bytes (0 switches on core 1)
```

**Comment by tpokorra** [comment]
more details:

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/share/lightbuildserver/web/lbs.py", line 86, in processbuildqueue
    self.LBS.ProcessBuildQueue()
  File "/usr/share/lightbuildserver/web/../lib/LightBuildServer.py", line 438, in ProcessBuildQueue
    self.CheckForHangingBuild()
  File "/usr/share/lightbuildserver/web/../lib/LightBuildServer.py", line 197, in CheckForHangingBuild
    cursor.execute(stmt, (row['id']))
ValueError: parameters are of unsupported type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.4/logging/__init__.py", line 978, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.4/logging/__init__.py", line 828, in format
    return fmt.format(record)
  File "/usr/lib64/python3.4/logging/__init__.py", line 565, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.4/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib/python3.4/site-packages/bottle.py", line 978, in __call__
    return self.wsgi(environ, start_response)
  File "/usr/lib/python3.4/site-packages/bottle.py", line 953, in wsgi
    out = self._cast(self._handle(environ))
  File "/usr/lib/python3.4/site-packages/bottle.py", line 861, in _handle
    return route.call(**args)
  File "/usr/lib/python3.4/site-packages/bottle.py", line 1727, in wrapper
    rv = callback(*a, **ka)
  File "/usr/share/lightbuildserver/web/lbs.py", line 88, in processbuildqueue
    logging.error("Unexpected error:", sys.exc_info()[0])
Message: 'Unexpected error:'
Arguments: (<class 'ValueError'>,)
```
