### ISSUE TITLE
still some jobs are not built

### ISSUE THREAD

**Issue by tpokorra** [SolidCharity/LightBuildServer#145]
they are triggered, but don't appear as failed or built. it is like they never existed

in the log file:

```
[00:20:49] Redirecting to /bin/systemctl stop  httpd.service
[00:20:50] LBSERROR: Setup script did not succeed
ReleaseMachine build02.lbs.solidcharity.com
[00:20:51] This build took about 20 minutes
GetAvailableBuildMachine found a free machine
[00:00:00]  * Starting at 2016-01-30 02:30:07 GMT+0100
[00:00:00]  * Preparing the machine...
GetAvailableBuildMachine found a free machine
[00:00:00]  * Starting at 2016-01-30 02:30:07 GMT+0100
[00:00:00]  * Preparing the machine...
Exception in thread Thread-26:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/lightbuildserver/web/../lib/Build.py", line 65, in buildpackage
    pathSrc=self.LBS.getPackagingInstructions(userconfig, username, projectname, branchname)
  File "/usr/share/lightbuildserver/web/../lib/LightBuildServer.py", line 306, in getPackagingInstructions
    self.getPackagingInstructionsInternal(userconfig, username, projectname, "master", gitprojectname, lbsproject, pathSrc)
  File "/usr/share/lightbuildserver/web/../lib/LightBuildServer.py", line 316, in getPackagingInstructionsInternal
    shutil.rmtree(pathSrc+'lbs-'+projectname)
  File "/usr/lib64/python3.4/shutil.py", line 464, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib64/python3.4/shutil.py", line 402, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib64/python3.4/shutil.py", line 402, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib64/python3.4/shutil.py", line 422, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib64/python3.4/shutil.py", line 420, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'rules'
```

**Comment by tpokorra** [comment]
two builds (for different architecture) building at the same time?
