### ISSUE TITLE
locked database prevents from build jobs being started

### ISSUE THREAD

**Issue by tpokorra** [SolidCharity/LightBuildServer#148]
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/share/lightbuildserver/web/lbs.py", line 86, in processbuildqueue
    self.LBS.ProcessBuildQueue()
  File "/usr/share/lightbuildserver/web/../lib/LightBuildServer.py", line 455, in ProcessBuildQueue
    self.attemptToFindBuildMachine(con, row)
  File "/usr/share/lightbuildserver/web/../lib/LightBuildServer.py", line 435, in attemptToFindBuildMachine
    buildmachine=self.GetAvailableBuildMachine(con,username,projectname,packagename,branchname,lxcdistro,lxcrelease,lxcarch,AvoidDocker,AvoidLXC)
  File "/usr/share/lightbuildserver/web/../lib/LightBuildServer.py", line 155, in GetAvailableBuildMachine
    cursor.execute(stmt)
sqlite3.OperationalError: database is locked
```

Later: 

```
stopping machine build02.lbs.solidcharity.com because of hanging build
ReleaseMachine build02.lbs.solidcharity.com
```

**Comment by tpokorra** [comment]
the question is why do we need an increased timeout? which query is blocking the database for so long?

**Comment by tpokorra** [comment]
is it the logs writing quite often to the database?

should we offer an alternative db access method for Mysql? modify ConnectDatabase

need to convert existing sqlite database to mysql? http://stackoverflow.com/a/1067365/1632368

**Comment by tpokorra** [comment]
Fedora23, mysql:

```
dnf install python-mysql mariadb-server
systemctl enable mariadb
systemctl start mariadb
mysql
    create database lbs;
    GRANT ALL ON lbs.* TO lbs IDENTIFIED BY 'secret';

sqlite3 /var/lib/lightbuildserver/db/lightbuildserver.db .dump > my.sql
# alter sql, drop begin transaction; commit; pragma ...; sequences, instead separate line ALTER TABLE build AUTO_INCREMENT=5000; drop autoincrement; drop log rows. replace char(400) with TEXT, replace release with backquote release. 
```
