### ISSUE TITLE
failure is not displayed on machine list, only on package view 

### ISSUE THREAD

**Issue by tpokorra** [SolidCharity/LightBuildServer#191]

**Comment by tpokorra** [comment]
```
MariaDB [lbs]> select * from build order by started desc limit 10;
+-------+----------+--------------+-------------+--------+----------------------------------+------------+--------+---------+-------+----------+-------------+------------------------+------------------------------------+---------------------+---------------------+---------+--------------+-------------+
| id    | status   | username     | projectname | secret | packagename                      | branchname | distro | release | arch  | avoidlxc | avoiddocker | dependsOnOtherProjects | buildmachine                       | started             | finished            | hanging | buildsuccess | buildnumber |
+-------+----------+--------------+-------------+--------+----------------------------------+------------+--------+---------+-------+----------+-------------+------------------------+------------------------------------+---------------------+---------------------+---------+--------------+-------------+
| 28966 | FINISHED | tpokorra     | lbs         | f      | lxc-scripts                      | master     | ubuntu | focal   | amd64 |        1 |           0 |                        | build04docker.lbs.solidcharity.com | 2020-09-19 06:41:01 | 2020-09-19 06:42:53 |       0 | success      |           3 |
| 28965 | FINISHED | tpokorra     | lbs         | f      | lxc-scripts                      | master     | ubuntu | focal   | amd64 |        1 |           0 |                        | build04docker.lbs.solidcharity.com | 2020-09-19 06:29:11 | 2020-09-19 06:31:48 |       0 | success      |           2 |
| 28955 | BUILDING | solidcharity | openpetra   | f      | openpetra-test-mysql             | test       | debian | buster  | amd64 |        0 |           1 |                        | build04lxd.lbs.solidcharity.com    | 2020-09-19 06:27:01 | 0000-00-00 00:00:00 |       0 | NULL         |        NULL |
```
there are 2 finished jobs
the 2 failed jobs look like if they are still building

**Comment by tpokorra** [comment]
the log looks like this:

```
[00:05:12] Permission denied, please try again.
[00:05:12] Permission denied, please try again.
[00:05:12] Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
[00:05:22] LBSERROR: Problem with startmachine
[00:05:36] This build took about 5 minutes

```

**Comment by tpokorra** [comment]
running lbs.py directly, it seems the ssh is waiting for the root password, and blocking the whole process.

**Comment by tpokorra** [comment]
when running directly from the console, I see this error:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./../lib/Build.py", line 230, in buildpackage
    self.logger.email(self.config['lbs']['EmailFromAddress'], userconfig['EmailToAddress'], "LBS Result for " + projectname + "/" + packagename, self.config['lbs']['LBSUrl'] + "/logs/" + logpath + "/" + str(buildnumber))
  File "./../lib/Logger.py", line 135, in email
    server.login(self.emailuser, self.emailpassword)
  File "/usr/lib64/python3.6/smtplib.py", line 730, in login
    raise last_exception
  File "/usr/lib64/python3.6/smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "/usr/lib64/python3.6/smtplib.py", line 642, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Error: authentication failed: authentication failure')
```
